name: Build exe file

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client-build.yml"
jobs:
  build-exe-file:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{matrix.os}}

    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"
          cache: "npm"
          cache-dependency-path: "./client/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Build typescript
        run: |
          npm i typescript
          npm run build

      - name: Build out.js file
        run: npm run package

      - name: Creating exe file
        run: |
          echo '{ "main": "out.js", "output": "node-cli.blob" }' > sea-config.json 
          node --experimental-sea-config sea-config.json

      - name: Prepare Executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./client
        run: |
          cp $(command -v node) chat
          npx postject chat NODE_SEA_BLOB node-cli.blob \
           --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2

      - name: Prepare Executable (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ./client
        shell: powershell
        run: |
          node -e "require('fs').copyFileSync(process.execPath, 'chat.exe')"
          signtool remove /s chat.exe
          npx postject chat.exe NODE_SEA_BLOB node-cli.blob \
           --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          signtool sign /fd SHA256 hello.exe

      - name: Uploading executable
        uses: actions/upload-artifact@v4
        with:
          name: single-exe
          path: |
            chat
            chat.exe
